name: Daily Field Reports Pipeline

on:
  schedule:
    # Run daily at 10:00 AM UTC
    - cron: '0 10 * * *'
  workflow_dispatch:  # Allow manual trigger

jobs:
  trigger-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Execute pipeline and auto-commit from Railway
        run: |
          echo "=== Field Reports Pipeline Daily Execution ==="
          echo "Time: $(date)"
          
          # Your Railway deployment URL
          RAILWAY_URL="https://web-production-c0c92.up.railway.app"
          
          echo "Step 1: Checking Railway service health..."
          curl -f "$RAILWAY_URL/health" --max-time 30 || echo "Service health check failed, but continuing..."
          
          echo "Step 2: Waiting 5 seconds for Railway service to be ready..."
          sleep 5
          
          echo "Step 3: Triggering pipeline execution with auto-commit..."
          response=$(curl -f "$RAILWAY_URL/api/github-actions/run-pipeline" --max-time 1800 -w "HTTP_CODE:%{http_code}")
          
          if [[ $response == *"HTTP_CODE:200"* ]]; then
            echo "✅ Pipeline execution and git commit completed successfully"
            echo "Response: $response"
          else
            echo "❌ Pipeline execution may have failed"
            echo "Response: $response"
            exit 1
          fi
