name: Daily Field Reports Pipeline

on:
  schedule:
    # Run daily at 10:00 AM UTC
    - cron: '0 10 * * *'
  workflow_dispatch:  # Allow manual trigger

jobs:
  trigger-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Execute pipeline and auto-commit from Replit
        run: |
          echo "=== Field Reports Pipeline Daily Execution ==="
          echo "Time: $(date)"
          
          # Your actual Replit URL
          REPLIT_URL="https://a1bf29b1-e0c7-4497-be02-3a0e5d7f681e-00-3e1832oiqv2xk.janeway.replit.dev"
          
          echo "Step 1: Waking up Replit service..."
          curl -f "$REPLIT_URL/health" --max-time 30 || echo "Service wake-up failed, but continuing..."
          
          echo "Step 2: Waiting 10 seconds for service to be ready..."
          sleep 10
          
          echo "Step 3: Triggering pipeline execution with auto-commit..."
          response=$(curl -f "$REPLIT_URL/api/github-actions/run-pipeline" --max-time 1800 -w "HTTP_CODE:%{http_code}")
          
          if [[ $response == *"HTTP_CODE:200"* ]]; then
            echo "✅ Pipeline execution and git commit completed successfully"
            echo "Response: $response"
          else
            echo "❌ Pipeline execution may have failed"
            echo "Response: $response"
            exit 1
          fi
